version: "3"
services:
  apache-php71:
    build: .
    ports:
      - "80:80"
#      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    tty: true
    stdin_open: true
    privileged: true
#    command: /sbin/init
